### ISSUE TITLE
Is porting to Armv8.0 underway? (If not, I'll start it)

### ISSUE THREAD

**Issue by malus-brandywine** [quic/gunyah-hypervisor#6]
Thank you!

**Comment by quic-cvanscha** [comment]
Hi Nataliya, thanks for your interest in Gunyah!
We did start some early work on ARMv8.0 support, however haven't had any time to continue it. We'd love you to contribute! As this could be a significant feature, I suggest we discuss the design & implementation details to make it easier to review and be accepted.

**Comment by malus-brandywine** [comment]
Hi Carl,
while working on switching off FEAT_VHE & FEAT_PAN I scribed a memory mapping illustration (attached, .png).

It looks like there's a conflict in the higher VA space: hyp. alloc space (8G) overlaps with some memory reservations for extra- root & private heap (yellow and orange on the chart). At least this is what I see at my current understanding of the components, so some design documents would be really helpful, please.

[The illustration](https://github.com/malus-brandywine/malus-brandywine/blob/master/gunyah/MemoryMappingAndUsage.png)

**Comment by quic-cvanscha** [comment]
Hi Nataliya,

Agreed, there is an issue and your understanding is correct. We didn't notice it previously since the number of hyp_aspace allocations being performed were not enough in practice to hit the overlap. We have done some refactoring recently to prevent this by allocating address ranges for the memory being added to the partition from the hyp_aspace allocator. This means that each memory range added to a partition has its own virt address and virt-phys offset. I don't have a timeline for when this will be contributed, however you may want to try workaround the issue for now.

As for general design...

The memory map design when using VHE and PAN is as such:
The higher VA space is used for hypervisor ASLR mappings, and the lower address space is primarily used for the physaccess (all of ddr) mapping area (VA is offset using HYP_ASPACE_PHYACCESS_OFFSET as you show), which is protected by PAN.

The physaccess region allows hypervisor to read memory from VMs efficiently, without dynamic map/unmap operations. E.g. A VM provided VA or IPA is translated to a PA (using CPU translation instructions or pgtable walks) and the PA offset by PHYACCESS_OFFSET to find the EL2 mapping. The PAN bit is temporarily cleared to allow a read/write of the VM buffer.

Without VHE and PAN, only the lower address space is available in EL2, so the memory map will obviously need some adjustment, and the physaccess region may not make sense, since without PAN, leaving the memory mapped and accessible all the time in EL2 opens up more possibility for bad addresses to mistakenly access VM memory.

**Comment by malus-brandywine** [comment]
Hi Carl,

Thank you for the clarification and apologies for delayed response.

My thesis on adjustments to memory mapping in non-VHE configuration. The guiding idea is to keep current logic/mechanisms (down to a single function) untouched as much as possible, and adjust configuration parameters. 

#### Memory layout

For non-VHE configuration, I would keep current memory layout (“hypervisor aspace”, “linear mapping”, “direct mapping”) even for single VA space. It would hopefully help to reduce the overhead for maintaining and debugging another layout.

Switching to single VA space while keeping the layout and address width reduces the space available for hypervisor. This can be solved by adding more bits to address width (in future). For the initial version of the port, I’d keep the current address width.

Configuration parameters affecting boundaries of the regions will be adjusted as well as virtual address of hypervisor image.

#### Translation tables

There will be one translation table tree (referenced by TTBR0_EL2).

**hyp_pgtable.top_control.root_pgtable/root** and **hyp_pgtable.bottom_control.root_pgtable/root** will point to the same table,
**hyp_pgtable.top_mask** will be “all zeros” or “all ones”.

#### ---

Any input will be appreciated !

I would implement this concept when new version of the code is available in github.

Thank you!

**Comment by quic-cvanscha** [comment]
The base code to support ARMv8.0 is now complete. We don't have an example platform or QEMU device to demonstrate it however. Please also note, Gunyah requires a platform with GICv3+ interrupt controller.
